package ru.bardinpetr.itmo.lab5.client.texts;

/**
 * Enum class for text access
 */
public enum TextKeys {
    GREEETING,
    HELP,
    WORKERINTERACT,
    NAMEINTERACT,
    COORDINATESINTERACT,
    SALARYINTERACT,
    STARTDAYINTERACT,
    ENDNDATEINTERACT,
    POSITIONINTERACT,
    ORGANIZATIONINTERACT,
    COORXINTERACT,
    COORYINTERACT,
    ORGANISATIONNAMEINTERACT,
    INVALID_APP_ARGUMENTS, FILEIO_ERROR_MESSAGE_TEMLPATE, ORGANISATIONTYPEINTERACT
}
